Txn relay fee
elementlabs42/BitVM pull request #13
Opened 2024-12-19 10:03 UTC by aristotleee

2025-01-16 14:03 UTC, franklynot requested changes

2025-01-16 14:03 UTC, franklynot commented on src/bridge/graphs/peg_out.rs
> +                        NamedTx {
Also, let's avoid having to type the tx name multiple times across the codebase. Let's add a `name()` method on the `BaseTransaction` struct:
```
pub trait BaseTransaction {
    fn name(&self) -> &'static str;

   // existing methods follow...
}
```

And let's define the following for the `NamedTx` struct and use it here instead of instantiating it manually:
```
impl NamedTx {
    pub fn for_tx(tx: &(impl BaseTransaction + PreSignedTransaction), confirmed: bool) -> Self {
        Self {
            txid: tx.tx().compute_txid(),
            name: tx.name(),
            confirmed,
        }
    }
}
`

2025-01-16 14:10 UTC, franklynot commented on src/bridge/client/client.rs
> +    pub fn get_data_mut(&mut self) -> &mut BitVMClientPublicData { &mut self.data }
Reading this again, let's just use the first option (i.e. drop the 'get' prefix).

2025-01-16 17:58 UTC, aristotleee commented on src/bridge/utils.rs
> +const NUM_BLOCKS_TESTNET: u32 = 0;
We need to change the regtest one back to 3, I see today some of the tests had non-final error which caused by timelock not expired.
Testnet with 0 was the old setting before refactor, we can use the same value

2025-01-16 18:06 UTC, aristotleee commented on src/bridge/graphs/peg_out.rs
> +            (Err(e), _) | (_, Err(e)) => Err(Error::Esplora(e)),
Right, then we need to return a special Error with two Errors combined. I don't think we need to bring in the complication here, plus esplora errors will most likely be a network error, resolves one resolves all.

2025-01-17 11:28 UTC, aristotleee commented on tests/bridge/client/fee.rs
> +fn get_peg_in_graph_mut(client: &mut BitVMClient, id: String) -> &mut PegInGraph {
let leave it for now, i'll add todo on this. There might be a refactor on the graph getter in client

2025-01-17 12:27 UTC, aristotleee commented on src/bridge/graphs/peg_out.rs
> +                        NamedTx {
has to use old format for peg in confirm, there is no peg in confirm object in peg out

2025-01-17 12:28 UTC, aristotleee commented on src/bridge/client/client.rs
> +                .verifier_status(&self.esplora, Some(context), &filtered_peg_outs)
in #28

2025-01-17 12:28 UTC, aristotleee commented on src/bridge/client/client.rs
> +    }
in #28

2025-01-17 12:28 UTC, aristotleee commented on src/bridge/client/client.rs
> +    fn find_peg_out_or_fail<'a>(
in #28

2025-01-17 12:28 UTC, aristotleee commented on src/bridge/client/client.rs
> +    async fn broadcast_tx(&self, finalize_result: &Result<Transaction, Error>) -> Txid {
in #28

2025-01-17 13:15 UTC, franklynot requested changes

2025-01-17 13:59 UTC, franklynot requested changes

2025-01-17 13:59 UTC, franklynot commented on src/bridge/client/client.rs
>      pub fn data_ref(&self) -> &BitVMClientPublicData { &self.data }
Also here 'ref' -> 🗑️

2025-01-17 14:10 UTC, franklynot approved these changes

2025-01-17 14:22 UTC, merged